name: Auto Merge
 
on:
  push:
    branches:
      - development
      - qa
 
permissions:
  contents: write
 
jobs:
 
  merge-development-to-qa:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout development
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: Merge development into qa
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
 
          git fetch origin
 
          git checkout qa
          git pull origin qa
 
          git merge origin/development --no-edit
 
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git qa
 
 
  merge-qa-to-main:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout qa
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: qa
 
      - name: Merge qa into main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
 
          git fetch origin
 
          git checkout main
          git pull origin main
 
          git merge origin/qa --no-edit
 
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git main
